apiVersion: v1
kind: Deployment
metadata:
  name: mysns
spec:
  selector:
    matchLabels:
      app: mysns
  replicas: 2
  template:
    metadata:
      labels:
        app: mysns
    spec:
      containers:
        - name: mysns
          image: 192.168.1.10:8443/mysns
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sns-service
spec:
  selector:
    app: mysns
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort